### PR TITLE
Add AASRiseTransitSetDetails2 class.

### PR DESCRIPTION
**Pull request by VPKSoft**
This adds the AASRiseTransitSetDetails2 class except for moon algorithms:
* ELP2000
* ELPMPP02Nominal
* ELPMPP02LLR
* ELPMPP02DE405
* ELPMPP02DE406

### CODE REVIEW

**Comment by VPKSoft** [comment]
Seems that they already were in the development branch😅

**Comment by elendil-software** [comment]
Sorry for this late response. I think I missed the notification.
I will look at your implementation and the one that is on the develop branch.

**Comment by VPKSoft** [comment]
Thanks for the new release. I made this PR and then noticed there already was one adding these features ☺️ Closing as useless.

**Comment by elendil-software** [comment]
Not so useless. At least it remind me to continue to maintain this project. :-)
There should be others releases. This one match the AA+ version 2.12 and the latest is 2.44.

**Pull request closed without merging**
